import type { PatchSpec } from './patchTypes';

export const PATCHES: PatchSpec[] = [
  {
    id: 'p01-sub-bass',
    nombre: 'Sub Bass Redondo',
    descripcion: 'Bajo oscuro, estable, sin modulación.',
    dificultad: 'facil',
    ensena: 'Filtro low-pass + envolvente corta',
    targets: [
      { controlId: 'CUTOFF',    value: 28,  required: true },
      { controlId: 'RESONANCE', value: 18,  required: true },
    ],
    pasos: [
      { orden: 1, instruccion: 'Selecciona INIT Program (SHIFT + WRITE > Init Program).' },
      { orden: 2, instruccion: 'Ajusta VCO1 y VCO2 a forma de onda SAW y octava 16\'.' },
      { orden: 3, instruccion: 'En el MIXER, sube VCO1 y VCO2 a ~90.' },
      { orden: 4, instruccion: 'Baja CUTOFF hasta ~28 (muy oscuro).', ayuda: 'El CUTOFF a 28/127 deja pasar solo las frecuencias más bajas.' },
      { orden: 5, instruccion: 'En AMP EG: ATTACK mínimo, DECAY ~35, SUSTAIN a 0 (sonido percusivo).'},
    ],
  },
  {
    id: 'p02-lead-vibrato',
    nombre: 'Lead Vibrato',
    descripcion: 'Lead brillante con vibrato suave.',
    dificultad: 'facil',
    ensena: 'LFO aplicado a PITCH',
    targets: [
      { controlId: 'CUTOFF',   value: 75, required: true },
      { controlId: 'LFO_RATE', value: 55, required: true },
      { controlId: 'LFO_INT',  value: 18, required: true },
    ],
    pasos: [
      { orden: 1, instruccion: 'Inicia desde INIT.' },
      { orden: 2, instruccion: 'VCO1 y VCO2 en forma TRI (triángulo), octava 8\'.' },
      { orden: 3, instruccion: 'FILTER: CUTOFF ~75, RESONANCE ~20.' },
      { orden: 4, instruccion: 'AMP EG: A=0, D=20, S=80, R=25.' },
      { orden: 5, instruccion: 'LFO TARGET → PITCH. RATE ~55, INT ~18.', ayuda: 'LFO TARGET se selecciona con SHIFT + tecla LFO TARGET.' },
      { orden: 6, instruccion: 'FX: DELAY ON, TIME ~35, DEPTH ~25.' },
    ],
  },
  {
    id: 'p03-pluck',
    nombre: 'Pluck Percusivo',
    descripcion: 'Sonido corto y articulado con carácter.',
    dificultad: 'facil',
    ensena: 'Envolvente corta + EG INT al filtro',
    targets: [
      { controlId: 'CUTOFF',    value: 45, required: true },
      { controlId: 'RESONANCE', value: 25, required: true },
      { controlId: 'EG_INT',    value: 104, required: true }, // 40 sobre base 64
    ],
    pasos: [
      { orden: 1, instruccion: 'Inicia desde INIT.' },
      { orden: 2, instruccion: 'VCO1: SQR (cuadrada), SHAPE ~80.' },
      { orden: 3, instruccion: 'FILTER: CUTOFF ~45, RESONANCE ~25, DRIVE ~50%.' },
      { orden: 4, instruccion: 'AMP EG: A=0, D=30, S=0, R=5.' },
      { orden: 5, instruccion: 'EG (mod): INT ~40 (positivo), TARGET=CUTOFF, D=35.', ayuda: 'EG INT a la derecha del CUTOFF, empuja el filtro hacia arriba al atacar la nota.' },
      { orden: 6, instruccion: 'FX: REVERB pequeño (TIME=25, DEPTH=20).' },
    ],
  },
  {
    id: 'p04-pad-lento',
    nombre: 'Pad Lento',
    descripcion: 'Pad suave con ataque largo y modulación lenta.',
    dificultad: 'media',
    ensena: 'Ataque largo + sustain alto',
    targets: [
      { controlId: 'CUTOFF',   value: 50, required: true },
      { controlId: 'LFO_RATE', value: 25, required: true },
      { controlId: 'LFO_INT',  value: 10, required: true },
    ],
    pasos: [
      { orden: 1, instruccion: 'Inicia desde INIT.' },
      { orden: 2, instruccion: 'VCO1: SAW, SHAPE=0. VCO2: SAW, PITCH ligeramente desafinado.' },
      { orden: 3, instruccion: 'FILTER: CUTOFF ~50, RESONANCE ~12.' },
      { orden: 4, instruccion: 'AMP EG: A=70, D=40, S=95, R=80.' },
      { orden: 5, instruccion: 'LFO TARGET → SHAPE. RATE ~25, INT ~10.', ayuda: 'Modulación lenta de SHAPE crea un movimiento sutil en el timbre.' },
      { orden: 6, instruccion: 'FX: MOD CHORUS, TIME=40, DEPTH=45.' },
    ],
  },
  {
    id: 'p05-pwm-pad',
    nombre: 'PWM Pad',
    descripcion: 'Pad con modulación de ancho de pulso.',
    dificultad: 'media',
    ensena: 'Modulación de SHAPE con onda cuadrada',
    targets: [
      { controlId: 'CUTOFF',    value: 55, required: true },
      { controlId: 'VCO1_SHAPE', value: 64, required: true },
      { controlId: 'LFO_RATE',  value: 18, required: true },
      { controlId: 'LFO_INT',   value: 28, required: false },
    ],
    pasos: [
      { orden: 1, instruccion: 'Inicia desde INIT.' },
      { orden: 2, instruccion: 'VCO1 y VCO2: SQR (cuadrada), SHAPE=64 (centro).' },
      { orden: 3, instruccion: 'LFO TARGET → SHAPE. WAVE=TRI, RATE ~18, INT ~28.' },
      { orden: 4, instruccion: 'FILTER: CUTOFF ~55.' },
      { orden: 5, instruccion: 'FX: MOD ENSEMBLE ON.' },
    ],
  },
  {
    id: 'p06-wah-lfo',
    nombre: 'Wah-Wah LFO',
    descripcion: 'Efecto wah automático clásico.',
    dificultad: 'media',
    ensena: 'LFO aplicado al CUTOFF',
    targets: [
      { controlId: 'CUTOFF',    value: 35, required: true },
      { controlId: 'RESONANCE', value: 45, required: true },
      { controlId: 'LFO_RATE',  value: 30, required: true },
      { controlId: 'LFO_INT',   value: 45, required: true },
    ],
    pasos: [
      { orden: 1, instruccion: 'Inicia desde INIT.' },
      { orden: 2, instruccion: 'FILTER: CUTOFF ~35, RESONANCE ~45.' },
      { orden: 3, instruccion: 'LFO TARGET → CUTOFF. WAVE=SAW, RATE ~30, INT ~45.', ayuda: 'La combinación de RESONANCE alta + LFO en CUTOFF crea el efecto "wah" clásico.' },
      { orden: 4, instruccion: 'AMP EG: S=90 (sustain alto para notas largas).' },
    ],
  },
  {
    id: 'p07-noise-snare',
    nombre: 'Noise Snare',
    descripcion: 'Caja de batería simulada con ruido.',
    dificultad: 'media',
    ensena: 'MULTI ENGINE NOISE + envolvente',
    targets: [
      { controlId: 'CUTOFF',   value: 65, required: true },
    ],
    pasos: [
      { orden: 1, instruccion: 'Inicia desde INIT.' },
      { orden: 2, instruccion: 'Selecciona MULTI ENGINE → NOISE y sube su nivel a ~90 en el MIXER.' },
      { orden: 3, instruccion: 'VCO1 y VCO2: nivel a 0 en el MIXER.' },
      { orden: 4, instruccion: 'FILTER: CUTOFF ~65, RESONANCE ~10.' },
      { orden: 5, instruccion: 'AMP EG: A=0, D=20, S=0, R=10.' },
      { orden: 6, instruccion: 'FX: REVERB pequeño.' },
    ],
  },
  {
    id: 'p08-hihat',
    nombre: 'Hi-Hat',
    descripcion: 'Charles/platillo simulado con ruido agudo.',
    dificultad: 'media',
    ensena: 'Ruido + filtro abierto + envolvente ultra corta',
    targets: [
      { controlId: 'CUTOFF', value: 95, required: true },
    ],
    pasos: [
      { orden: 1, instruccion: 'Inicia desde INIT.' },
      { orden: 2, instruccion: 'MULTI ENGINE → NOISE, nivel máximo en MIXER.' },
      { orden: 3, instruccion: 'FILTER: CUTOFF ~95 (casi completamente abierto).' },
      { orden: 4, instruccion: 'AMP EG: A=0, D=10, S=0, R=5.' },
    ],
  },
  {
    id: 'p09-ring-mod',
    nombre: 'Ring Mod Metálico',
    descripcion: 'Sonido metálico e inarmónico con ring modulation.',
    dificultad: 'alta',
    ensena: 'RING modulation + armónicos',
    targets: [
      { controlId: 'CUTOFF',    value: 70, required: true },
      { controlId: 'RESONANCE', value: 30, required: true },
    ],
    pasos: [
      { orden: 1, instruccion: 'Inicia desde INIT.' },
      { orden: 2, instruccion: 'VCO1: TRI. VCO2: SQR, PITCH ~72 (sube ~8 semis).' },
      { orden: 3, instruccion: 'Activa RING en la sección de modulación (SHIFT + tecla RING).', ayuda: 'RING multiplica las señales de VCO1 y VCO2 creando parciales inarmónicos.' },
      { orden: 4, instruccion: 'FILTER: CUTOFF ~70, RES ~30, DRIVE ~50%.' },
      { orden: 5, instruccion: 'AMP EG: A=0, D=25, S=70, R=30.' },
    ],
  },
  {
    id: 'p10-sync-lead',
    nombre: 'Sync Lead',
    descripcion: 'Lead brillante con oscilador sincronizado.',
    dificultad: 'alta',
    ensena: 'SYNC y barrido de forma de onda',
    targets: [
      { controlId: 'CUTOFF', value: 78, required: true },
      { controlId: 'EG_INT', value: 114, required: true }, // +50
    ],
    pasos: [
      { orden: 1, instruccion: 'Inicia desde INIT.' },
      { orden: 2, instruccion: 'VCO1: SAW. VCO2: SAW, PITCH ~80.' },
      { orden: 3, instruccion: 'Activa SYNC (SHIFT + tecla SYNC).', ayuda: 'SYNC reinicia VCO2 en cada ciclo de VCO1, creando timbres brillantes y agresivos.' },
      { orden: 4, instruccion: 'FILTER: CUTOFF ~78.' },
      { orden: 5, instruccion: 'EG: INT ~+50, TARGET=PITCH.' },
    ],
  },
  {
    id: 'p11-chord-stab',
    nombre: 'Chord Stab',
    descripcion: 'Acorde percusivo en una sola nota.',
    dificultad: 'media',
    ensena: 'Voice Mode CHORD',
    targets: [
      { controlId: 'CUTOFF',    value: 55, required: true },
      { controlId: 'RESONANCE', value: 18, required: true },
    ],
    pasos: [
      { orden: 1, instruccion: 'Inicia desde INIT.' },
      { orden: 2, instruccion: 'Activa Voice Mode → CHORD (botón VOICE MODE).' },
      { orden: 3, instruccion: 'FILTER: CUTOFF ~55, RES ~18.' },
      { orden: 4, instruccion: 'AMP EG: A=0, D=25, S=0, R=10.' },
      { orden: 5, instruccion: 'FX: DELAY suave.' },
    ],
  },
  {
    id: 'p12-arp-sparkle',
    nombre: 'Arp Sparkle',
    descripcion: 'Arpegio brillante con delay rítmico.',
    dificultad: 'media',
    ensena: 'Modo ARP + delay',
    targets: [
      { controlId: 'CUTOFF',   value: 80, required: true },
      { controlId: 'FX_DEPTH', value: 35, required: false },
    ],
    pasos: [
      { orden: 1, instruccion: 'Inicia desde INIT.' },
      { orden: 2, instruccion: 'Activa Voice Mode → ARP.' },
      { orden: 3, instruccion: 'FILTER: CUTOFF ~80, RESONANCE baja.' },
      { orden: 4, instruccion: 'FX: DELAY, TIME sincronizado con BPM si es posible.' },
    ],
  },
  {
    id: 'p13-vpm-glass',
    nombre: 'VPM Glass',
    descripcion: 'Timbre cristalino con síntesis VPM.',
    dificultad: 'alta',
    ensena: 'MULTI ENGINE VPM',
    targets: [
      { controlId: 'CUTOFF',    value: 85, required: true },
      { controlId: 'VCO2_SHAPE', value: 75, required: false },
    ],
    pasos: [
      { orden: 1, instruccion: 'Inicia desde INIT.' },
      { orden: 2, instruccion: 'MULTI ENGINE → VPM, selecciona un tipo (explora los 16).', ayuda: 'VPM es síntesis FM básica. Distintos tipos dan diferentes caracteres metálicos o cristalinos.' },
      { orden: 3, instruccion: 'MULTI SHAPE ~75. Niveles VCO1/VCO2 bajos en MIXER.' },
      { orden: 4, instruccion: 'FILTER: CUTOFF ~85.' },
      { orden: 5, instruccion: 'FX: REVERB hall grande.' },
    ],
  },
  {
    id: 'p14-drone',
    nombre: 'Drone Cinemático',
    descripcion: 'Textura larga y evolucionante para atmósferas.',
    dificultad: 'alta',
    ensena: 'Sustain largo + modulación lenta',
    targets: [
      { controlId: 'CUTOFF',   value: 40, required: true },
      { controlId: 'RESONANCE', value: 35, required: true },
      { controlId: 'LFO_RATE', value: 10, required: true },
      { controlId: 'LFO_INT',  value: 20, required: true },
    ],
    pasos: [
      { orden: 1, instruccion: 'Inicia desde INIT.' },
      { orden: 2, instruccion: 'AMP EG: A=60, D=0, S=127, R=80.' },
      { orden: 3, instruccion: 'FILTER: CUTOFF ~40, RES ~35.' },
      { orden: 4, instruccion: 'LFO TARGET → CUTOFF. WAVE=TRI, RATE ~10, INT ~20.', ayuda: 'Con RATE tan bajo, el LFO tarda varios segundos en completar un ciclo.' },
      { orden: 5, instruccion: 'FX: REVERB arena (o hall).' },
    ],
  },
  {
    id: 'p15-acid-bass',
    nombre: 'Acid-ish Resonant Bass',
    descripcion: 'Bajo ácido con resonancia exagerada.',
    dificultad: 'alta',
    ensena: 'Resonancia alta + EG en filtro',
    targets: [
      { controlId: 'CUTOFF',    value: 35,  required: true },
      { controlId: 'RESONANCE', value: 75,  required: true },
      { controlId: 'EG_INT',    value: 134, required: true }, // +70
    ],
    pasos: [
      { orden: 1, instruccion: 'Inicia desde INIT.' },
      { orden: 2, instruccion: 'FILTER: CUTOFF ~35, RESONANCE ~75, DRIVE al máximo.', ayuda: 'RESONANCE tan alta lleva el filtro casi a la auto-oscilación — el timbre "pica".' },
      { orden: 3, instruccion: 'EG: INT ~+70, TARGET=CUTOFF, A=0, D=40.' },
      { orden: 4, instruccion: 'AMP EG: A=0, D=35, S=0, R=10.' },
    ],
  },
];
